version: "3.8"

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - app-volumes:/src
    command: air ./main.go -b 0.0.0.0
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - app-volumes:/var/lib/postgresql/data

volumes:
  app-volumes:
