version: "3.8"

services:
  unit:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - app-test-volumes:/src/tests
    command: go test ./src/tests
    depends_on:
      - db
    links:
      - db

  db:
    container_name: db
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    ports:
      - "${TEST_DB_PORT}:5432"

volumes:
  app-test-volumes:
